-- Every rule of the SQL importer, hand-written: types, defaults, checks,
-- enums, arrays, json, notes, references, unions, embedded records, child
-- tables, keys, uniques, indexes, comments, names, and dropped statements.

SET search_path = store, public;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE SCHEMA store;
CREATE TYPE store.mood AS ENUM ('sad', 'ok');
CREATE SEQUENCE store.ticket_seq;
GRANT USAGE ON SCHEMA store TO app;

CREATE TABLE store.everything (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  flag boolean NOT NULL DEFAULT false,
  small smallint NOT NULL,
  count integer NOT NULL DEFAULT 3 CHECK (count >= 0 AND count <= 100),
  big bigint CHECK (big > 0),
  under integer NOT NULL CHECK (under < 10),
  score integer NOT NULL CHECK (score BETWEEN 1 AND 5),
  ratio real NOT NULL,
  exact double precision NOT NULL CHECK (exact <= 1.5),
  price numeric(10, 2) NOT NULL DEFAULT 1.50,
  whole numeric(12),
  amount numeric,
  cash money,
  label text NOT NULL DEFAULT 'n/a' CHECK (char_length(label) >= 2) CHECK (char_length(label) <= 8),
  name varchar(64) NOT NULL,
  code char(3),
  email text NOT NULL CHECK (email ~ '^[^@]+@[^@]+$'),
  handle text CHECK (handle ~* '^[a-z]+$'),
  nick citext,
  addr inet,
  spot point,
  blob bytea CHECK (octet_length(blob) <= 1024),
  day date,
  tod time without time zone,
  zoned time with time zone,
  at timestamp with time zone NOT NULL DEFAULT now(),
  stamp timestamp,
  took interval,
  seq serial,
  ticket bigserial,
  n integer GENERATED BY DEFAULT AS IDENTITY,
  doubled integer GENERATED ALWAYS AS (count * 2) STORED,
  raw json,
  doc jsonb,
  legacy varchar(36),  -- schemata: uuid?
  tags text[] NOT NULL,  -- schemata: list<string(max = 16)>
  plain integer[],
  attributes jsonb NOT NULL,  -- schemata: map<string, string>
  history jsonb,  -- schemata: list<Visit>
  "Mixed Case" text,
  "record" text,
  CHECK (count <> 13)
);

COMMENT ON TABLE store.everything IS 'One column of every kind.';
COMMENT ON COLUMN store.everything.label IS 'Two to eight characters.';

CREATE TABLE store.customer (
  tenant_id uuid NOT NULL,
  code varchar(16) NOT NULL,
  name text NOT NULL,
  CONSTRAINT pk_customer PRIMARY KEY (code, tenant_id)
);

COMMENT ON TABLE store.customer IS 'A customer, keyed by code within a tenant.';

CREATE TABLE store."Order" (
  id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status = ANY (ARRAY['pending'::text, 'Paid-Out'::text])),
  customer_code varchar(16) NOT NULL,
  customer_tenant_id uuid NOT NULL,
  backup_code varchar(16),
  backup_tenant_id uuid,
  parent_id uuid REFERENCES store."Order" (id) ON DELETE SET NULL,
  origin uuid REFERENCES geo.region (id),
  region_id uuid REFERENCES geo.region (id),
  warehouse_id uuid REFERENCES elsewhere.warehouse (id),
  payment_kind text NOT NULL,
  payment_card_last4 varchar(4),
  payment_card_brand varchar(32),
  payment_cash_note text,
  payment_uuid uuid,
  payment_voucher text,
  payment_customer_code varchar(16),
  payment_customer_tenant_id uuid,
  refund_kind text,
  refund_card_last4 varchar(4),
  refund_card_brand varchar(32),
  refund_uuid uuid,
  home_street varchar(200),
  home_zip text,
  away_street text,
  away_zip text,
  CONSTRAINT pk_order PRIMARY KEY (id),
  CONSTRAINT ck_order_backup_present CHECK (((backup_code IS NULL AND backup_tenant_id IS NULL) OR (backup_code IS NOT NULL AND backup_tenant_id IS NOT NULL))),
  CONSTRAINT ck_order_payment_kind CHECK (payment_kind IN ('card', 'cash', 'uuid', 'voucher', 'customer')),
  CONSTRAINT ck_order_payment_card CHECK ((payment_kind <> 'card') OR (payment_card_last4 IS NOT NULL AND payment_card_brand IS NOT NULL)),
  CONSTRAINT ck_order_payment_uuid CHECK ((payment_kind <> 'uuid') OR (payment_uuid IS NOT NULL)),
  CONSTRAINT ck_order_payment_voucher_enum CHECK (payment_voucher IN ('gift', 'promo')),
  CONSTRAINT ck_order_payment_voucher CHECK ((payment_kind <> 'voucher') OR (payment_voucher IS NOT NULL)),
  CONSTRAINT ck_order_payment_customer CHECK ((payment_kind <> 'customer') OR (payment_customer_code IS NOT NULL AND payment_customer_tenant_id IS NOT NULL)),
  CONSTRAINT ck_order_refund_kind CHECK (refund_kind IN ('card', 'uuid')),
  CONSTRAINT ck_order_refund_card CHECK ((refund_kind <> 'card') OR (refund_card_last4 IS NOT NULL AND refund_card_brand IS NOT NULL)),
  CONSTRAINT ck_order_refund_uuid CHECK ((refund_kind <> 'uuid') OR (refund_uuid IS NOT NULL)),
  CONSTRAINT ck_order_home_zip_min CHECK (char_length(home_zip) >= 5),
  CONSTRAINT ck_order_home_present CHECK (((home_street IS NULL AND home_zip IS NULL) OR (home_street IS NOT NULL AND home_zip IS NOT NULL))),
  CONSTRAINT uq_order_customer UNIQUE (customer_code, customer_tenant_id),
  CONSTRAINT uq_order_status_zip UNIQUE (status, home_zip)
);

ALTER TABLE ONLY store."Order"
  ADD CONSTRAINT fk_order_customer FOREIGN KEY (customer_code, customer_tenant_id)
    REFERENCES store.customer (code, tenant_id);
ALTER TABLE ONLY store."Order"
  ADD CONSTRAINT fk_order_backup FOREIGN KEY (backup_code, backup_tenant_id)
    REFERENCES store.customer (code, tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY store."Order"
  ADD CONSTRAINT fk_order_payment_customer FOREIGN KEY (payment_customer_code, payment_customer_tenant_id)
    REFERENCES store.customer (code, tenant_id);

CREATE INDEX ix_order_payment ON store."Order" (payment_kind, payment_card_last4, payment_card_brand, payment_cash_note, payment_uuid, payment_voucher, payment_customer_code, payment_customer_tenant_id);
CREATE UNIQUE INDEX ON store."Order" (status) WHERE status = 'pending';
CREATE INDEX ON store."Order" USING hash (home_zip);
CREATE INDEX ON store."Order" ((lower(home_street)));
CREATE INDEX ix_order_away ON store."Order" (away_street, away_zip);

COMMENT ON TABLE store."Order" IS 'An order.';
COMMENT ON COLUMN store."Order".customer_code IS 'Who placed it.';
COMMENT ON COLUMN store."Order".payment_kind IS 'How it was paid.';
COMMENT ON COLUMN store."Order".home_street IS 'Where it goes.';

CREATE TABLE store."Order_lines" (
  "Order_id" uuid NOT NULL,
  position integer NOT NULL,
  sku varchar(64) NOT NULL,
  quantity integer NOT NULL CHECK (quantity >= 1),
  PRIMARY KEY ("Order_id", position)
);

CREATE TABLE store."Order_lines_notes" (
  "Order_lines_Order_id" uuid NOT NULL,
  "Order_lines_position" integer NOT NULL,
  position integer NOT NULL,
  value text NOT NULL,
  PRIMARY KEY ("Order_lines_Order_id", "Order_lines_position", position),
  FOREIGN KEY ("Order_lines_Order_id", "Order_lines_position")
    REFERENCES store."Order_lines" ("Order_id", position) ON DELETE CASCADE
);

CREATE TABLE store."Order_tags" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id) ON DELETE CASCADE,
  position integer NOT NULL,
  value varchar(16) NOT NULL,
  PRIMARY KEY ("Order_id", position)
);

CREATE TABLE store."Order_statuses" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id) ON DELETE CASCADE,
  position integer NOT NULL,
  value text NOT NULL CHECK (value IN ('open', 'closed')),
  PRIMARY KEY ("Order_id", position)
);

CREATE TABLE store."Order_prices" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id) ON DELETE CASCADE,
  key text NOT NULL,
  value numeric(10, 2) NOT NULL,
  PRIMARY KEY ("Order_id", key)
);

CREATE TABLE store."Order_regions" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id) ON DELETE CASCADE,
  position integer NOT NULL,
  value_id uuid,
  PRIMARY KEY ("Order_id", position),
  FOREIGN KEY (value_id) REFERENCES geo.region (id)
);

CREATE TABLE store."Order_stops" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id) ON DELETE CASCADE,
  key integer NOT NULL,
  value_street text,
  value_zip text,
  PRIMARY KEY ("Order_id", key),
  CHECK (((value_street IS NULL AND value_zip IS NULL) OR (value_street IS NOT NULL AND value_zip IS NOT NULL)))
);

CREATE TABLE store."Order_audit" (
  "Order_id" uuid NOT NULL REFERENCES store."Order" (id),
  position integer NOT NULL,
  note text,
  PRIMARY KEY ("Order_id", position)
);

ALTER TABLE store."Order_lines"
  ADD FOREIGN KEY ("Order_id") REFERENCES store."Order" (id) ON DELETE CASCADE;

COMMENT ON TABLE store."Order_lines" IS 'One purchasable item.';
COMMENT ON COLUMN store."Order_lines".sku IS 'The stock-keeping unit.';

CREATE TABLE store.booking (
  id uuid PRIMARY KEY,
  during tstzrange NOT NULL,
  EXCLUDE USING gist (during WITH &&)
) INHERITS (store.base);

CREATE VIEW store.pending AS SELECT id FROM store."Order" WHERE status = 'pending';
CREATE FUNCTION store.touch() RETURNS trigger AS $$ BEGIN RETURN NEW; END $$ LANGUAGE plpgsql;
CREATE TRIGGER touch BEFORE UPDATE ON store."Order" FOR EACH ROW EXECUTE FUNCTION store.touch();
ALTER TABLE store."Order" OWNER TO app;
