[package]
name = "Schemata"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"]}
pest = "2.6.1"
pest_derive = "2.6.1"
protobuf = "2.28.0"
avro-rs = "0.13.0"
quick-xml = "^0.27"
log = "0.4.22"
env_logger = "0.11.5"