[versions]
kotlin = "2.1.20"
antlr = "4.13.2"
clikt = "5.0.2"
testcontainers = "1.20.4"
postgresJdbc = "42.7.4"
protobuf = "4.29.3"
spotless = "7.0.2"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotlessGradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
antlrTool = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlrRuntime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
testcontainersPostgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
postgresJdbc = { module = "org.postgresql:postgresql", version.ref = "postgresJdbc" }
