package io.schemata.cli.guide

import io.schemata.cli.Pipeline
import io.schemata.cli.diagnostics.Fixture
import io.schemata.core.CoreCodes
import io.schemata.lang.DiagnosticCode
import io.schemata.lang.LangCodes
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * `guide/diagnostics.md` and `guide/annotations.md` are rendered from the compiler and compared as
 * goldens.
 */
class GuideAppendicesTest {
    private val banner = "<!-- generated by GuideAppendicesTest; do not edit -->\n"

    @Test
    fun `diagnostics appendix is current`() {
        Guide.golden(File(Guide.dir, "diagnostics.md"), banner + diagnostics())
    }

    @Test
    fun `annotations appendix is current`() {
        Guide.golden(File(Guide.dir, "annotations.md"), banner + annotations())
    }

    @Test
    fun `stripLocation drops only a leading element location`() {
        assertEquals(
            "strategy 'embed' is not allowed for a list",
            stripLocation("record 'R' field 'x': strategy 'embed' is not allowed for a list"),
        )
        assertEquals("unknown type 'X'", stripLocation("unknown type 'X'"))
    }

    private data class Module(
        val title: String,
        val prefix: String,
        val codes: List<DiagnosticCode>,
        val retired: List<String>,
    )

    private fun modules() =
        listOf(
            Module("Syntax (SCH0xxx)", "SCH0", LangCodes.all, emptyList()),
            Module("Semantics (SCH1xxx)", "SCH1", CoreCodes.all, listOf("SCH1007", "SCH1008")),
            Module(
                "Protobuf (SCH20xx)",
                "SCH20",
                Pipeline.targetNamed("proto")!!.codes,
                listOf("SCH2002", "SCH2003"),
            ),
            Module(
                "Postgres (SCH21xx)",
                "SCH21",
                Pipeline.targetNamed("sql")!!.codes,
                listOf("SCH2103", "SCH2104"),
            ),
        )

    private fun diagnostics(): String = buildString {
        appendLine("# Diagnostics")
        appendLine()
        appendLine(
            "Every code the compiler can report, with the message shapes and help text its fixtures show. `schemata --strict` promotes warnings to errors."
        )
        val fixtures = Fixture.all().groupBy { it.code }
        for (m in modules()) {
            appendLine()
            appendLine("## ${m.title}")
            appendLine()
            appendLine("| Code | Severity | Fires when | Message | Help |")
            appendLine("|---|---|---|---|---|")
            for (c in m.codes.sortedBy { it.id }) {
                val shapes = fixtures[c.id].orEmpty().sortedBy { it.name }
                val messages = shapes.flatMap { messagesOf(it.expected) }.distinct()
                val helps = shapes.flatMap { helpsOf(it.expected) }.distinct()
                val severity =
                    c.severity.name.lowercase() + if (c.category.name == "LOSSY") " (lossy)" else ""
                appendLine(
                    "| ${c.id} | $severity | ${c.description} | ${cell(messages)} | ${cell(helps)} |"
                )
            }
            if (m.retired.isNotEmpty()) {
                appendLine()
                appendLine("Retired, never reused: ${m.retired.joinToString(", ")}.")
            }
        }
    }

    private fun messagesOf(expected: String) =
        expected
            .lines()
            .filter { it.startsWith("error[") || it.startsWith("warning[") }
            .map { stripLocation(it.substringAfter("]").substringAfter(": ")) }

    /**
     * Drops the `record 'R' field 'x': ` location prefix a target message carries so the shape
     * reads generally.
     */
    private fun stripLocation(message: String): String =
        if (
            Regex("^(record|field|enum|union|namespace|alias) '").containsMatchIn(message) &&
                message.contains("': ")
        )
            message.substringAfter("': ")
        else message

    private fun helpsOf(expected: String) =
        expected
            .lines()
            .map { it.trim() }
            .filter { it.startsWith("= help: ") }
            .map { it.removePrefix("= help: ") }

    private fun cell(items: List<String>) = items.joinToString("<br>") { escape(it) }

    private fun escape(s: String) = s.replace("|", "\\|")

    private fun annotations(): String = buildString {
        appendLine("# Annotations")
        appendLine()
        appendLine(
            "Keys each target accepts, the elements they apply to, and the codes each target can report. `schemata targets --format json` prints the same data."
        )
        for (t in Pipeline.targets) {
            appendLine()
            appendLine("## @${t.name}")
            appendLine()
            appendLine("| Key | Applies to | Value | Choices | Optional |")
            appendLine("|---|---|---|---|---|")
            for (s in t.annotationSpecs) {
                val elements =
                    s.elements.sortedBy { it.ordinal }.joinToString(", ") { it.displayName }
                val choices = s.choices?.sorted()?.joinToString(", ") ?: ""
                appendLine(
                    "| `${s.key}` | $elements | ${s.valueKind.name.lowercase()} | $choices | ${if (s.optional) "yes" else "no"} |"
                )
            }
            appendLine()
            appendLine(
                "Codes: " + t.codes.joinToString(", ") { "${it.id} (${it.description})" } + "."
            )
        }
    }
}
