package io.schemata.cli.guide

import io.schemata.cli.Pipeline
import io.schemata.cli.diagnostics.Fixture
import io.schemata.core.CoreCodes
import io.schemata.evolution.EvolutionCodes
import io.schemata.importer.ImportCodes
import io.schemata.lang.DiagnosticCode
import io.schemata.lang.LangCodes
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * `guide/diagnostics.md` and `guide/annotations.md` are rendered from the compiler and compared as
 * goldens.
 */
class GuideAppendicesTest {
    private val banner = "<!-- generated by GuideAppendicesTest; do not edit -->\n"

    @Test
    fun `diagnostics appendix is current`() {
        Guide.golden(File(Guide.dir, "diagnostics.md"), banner + diagnostics())
    }

    @Test
    fun `annotations appendix is current`() {
        Guide.golden(File(Guide.dir, "annotations.md"), banner + annotations())
    }

    @Test
    fun `stripLocation drops only a leading element location`() {
        assertEquals(
            "strategy 'embed' is not allowed for a list",
            stripLocation("record 'R' field 'x': strategy 'embed' is not allowed for a list"),
        )
        assertEquals("unknown type 'X'", stripLocation("unknown type 'X'"))
        assertEquals(
            "field 'q' cannot be a query parameter",
            stripLocation("operation 'find': field 'q' cannot be a query parameter"),
        )
    }

    private data class Module(
        val title: String,
        val prefix: String,
        val codes: List<DiagnosticCode>,
        val retired: List<String>,
    )

    private fun modules() =
        listOf(
            Module("Syntax (SCH0xxx)", "SCH0", LangCodes.all, emptyList()),
            Module("Semantics (SCH1xxx)", "SCH1", CoreCodes.all, listOf("SCH1007", "SCH1008")),
            Module(
                "Protobuf (SCH20xx)",
                "SCH20",
                Pipeline.targetNamed("proto")!!.codes,
                listOf("SCH2002", "SCH2003"),
            ),
            Module(
                "Postgres (SCH21xx)",
                "SCH21",
                Pipeline.targetNamed("sql")!!.codes,
                listOf("SCH2103", "SCH2104"),
            ),
            Module("XSD (SCH22xx)", "SCH22", Pipeline.targetNamed("xsd")!!.codes, emptyList()),
            Module(
                "JSON Schema (SCH23xx)",
                "SCH23",
                Pipeline.targetNamed("jsonschema")!!.codes,
                emptyList(),
            ),
            Module("Import (SCH24xx)", "SCH24", ImportCodes.all, emptyList()),
            Module("Evolution (SCH25xx)", "SCH25", EvolutionCodes.all, emptyList()),
            Module(
                "OpenAPI (SCH26xx)",
                "SCH26",
                Pipeline.targetNamed("openapi")!!.codes,
                emptyList(),
            ),
        )

    private fun diagnostics(): String = buildString {
        appendLine("# Diagnostics")
        appendLine()
        appendLine(
            "Every code the compiler can report, with the message shapes and help text its fixtures show. `compile --strict` (or `check --strict`) promotes warnings to errors."
        )
        val fixtures = Fixture.all().groupBy { it.code }
        for (m in modules()) {
            appendLine()
            appendLine("## ${m.title}")
            appendLine()
            appendLine("| Code | Severity | Category | Fires when | Message | Help |")
            appendLine("|---|---|---|---|---|---|")
            for (c in m.codes.sortedBy { it.id }) {
                val shapes = fixtures[c.id].orEmpty().sortedBy { it.name }
                val messages = shapes.flatMap { messagesOf(it.expected, c.id) }.distinct()
                val helps = shapes.flatMap { helpsOf(it.expected, c.id) }.distinct()
                val severity = c.severity.name.lowercase()
                val category = c.category.name.lowercase()
                appendLine(
                    "| ${c.id} | $severity | $category | ${c.description} | ${cell(messages)} | ${cell(helps)} |"
                )
            }
            if (m.retired.isNotEmpty()) {
                appendLine()
                appendLine("Retired, never reused: ${m.retired.joinToString(", ")}.")
            }
        }
    }

    /** The code named in a header line's `[…]`, such as `SCH1010` in `warning[SCH1010] ...`. */
    private fun headerCode(line: String): String? =
        Regex("^(?:error|warning)\\[([^]]+)]").find(line)?.groupValues?.get(1)

    /** The header messages in [expected] whose own code is [id]; a fixture may carry others too. */
    private fun messagesOf(expected: String, id: String) =
        expected
            .lines()
            .filter { headerCode(it) == id }
            .map { stripLocation(it.substringAfter("]").substringAfter(": ")) }

    /** The quoted-name location prefixes (`record 'R' field 'x': `, `element 'x': `, …). */
    private val quotedLocation =
        Regex(
            "^(record|field|enum value|enum|union|namespace|alias|complex type|simple type|" +
                "element|attribute|message|service|operation|table|column) '"
        )

    /**
     * The bare `<file>: ` or `<file>:<line>:<col>: ` prefix an import-level diagnostic (not tied to
     * one construct) carries.
     */
    private val fileLocation = Regex("^\\S+\\.(xsd|proto|sql)(:\\d+:\\d+)?: ")

    /** An evolution diagnostic's `<target>: <ns.Decl.member>: ` prefix. */
    private val evolutionLocation = Regex("^[a-z]+: [A-Za-z0-9_.#]+: ")

    /**
     * Drops a message's leading location — `record 'R' field 'x': `, `complex type 'X': `, `element
     * 'x': `, `operation 'x': `, `attribute 'x': `, `simple type 'X': `, `union 'X': `, `enum value
     * 'X.v': `, a bare `<file>: `, or an evolution diagnostic's `<target>: <path>: ` — so the shape
     * reads generally.
     */
    private fun stripLocation(message: String): String =
        when {
            quotedLocation.containsMatchIn(message) && message.contains("': ") ->
                message.substringAfter("': ")
            fileLocation.containsMatchIn(message) -> message.replaceFirst(fileLocation, "")
            evolutionLocation.containsMatchIn(message) ->
                message.replaceFirst(evolutionLocation, "")
            else -> message
        }

    /** The `= help: ` lines that follow an [id] header, up to the next blank line. */
    private fun helpsOf(expected: String, id: String): List<String> {
        val helps = mutableListOf<String>()
        var inBlock = false
        for (line in expected.lines()) {
            val code = headerCode(line)
            when {
                code != null -> inBlock = code == id
                line.isBlank() -> inBlock = false
                inBlock && line.trim().startsWith("= help: ") ->
                    helps += line.trim().removePrefix("= help: ")
            }
        }
        return helps
    }

    private fun cell(items: List<String>) = items.joinToString("<br>") { escape(it) }

    private fun escape(s: String) = s.replace("|", "\\|")

    private fun annotations(): String = buildString {
        appendLine("# Annotations")
        appendLine()
        appendLine(
            "Keys each target accepts, the elements they apply to, and the codes each target can report. `schemata targets --format json` prints the same data."
        )
        for (t in Pipeline.targets) {
            appendLine()
            appendLine("## @${t.name}")
            appendLine()
            appendLine("| Key | Applies to | Value | Choices |")
            appendLine("|---|---|---|---|")
            for (s in t.annotationSpecs) {
                val elements =
                    s.elements.sortedBy { it.ordinal }.joinToString(", ") { it.displayName }
                val choices = s.choices?.sorted()?.joinToString(", ") ?: ""
                appendLine(
                    "| `${s.key}` | $elements | ${s.valueKind.name.lowercase()} | $choices |"
                )
            }
            appendLine()
            appendLine("Codes:")
            appendLine()
            appendLine("| Code | Severity | Category | Description |")
            appendLine("|---|---|---|---|")
            for (c in t.codes.sortedBy { it.id }) {
                appendLine(
                    "| ${c.id} | ${c.severity.name.lowercase()} | ${c.category.name.lowercase()} | ${c.description} |"
                )
            }
        }
    }
}
